name: Github Pages

# By default, runs if you push to main. keeps your deployed app in sync with main branch.
on:
  push:
    branches:
      - main
# to only run when you do a new github release, comment out above part and uncomment the below trigger.
# on:
#   release:
#     types:
#       - published

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-github-pages:
    runs-on: windows-latest
    env:
      SLANG_DIR: ${{ github.workspace }}/slang
    steps:
      - uses: actions/checkout@v4 # repo checkout
      - name: Download latest Slang release
        uses: robinraju/release-downloader@v1
        with:
          repository: 'shader-slang/slang'
          latest: true
          fileName: 'slang-*-windows-x86_64.zip'
          out-file-path: 'slang'
          extract: true
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Setup toolchain for wasm
        run: |
          cargo install wasm-bindgen-cli
      - name: Rust Cache # cache the rust build artifacts
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --target wasm32-unknown-unknown
      - name: Bindgen
        run: wasm-bindgen --out-dir target/generated/ --web target/wasm32-unknown-unknown/debug/slang-voxels.wasm 
      - name: Move files
        run: |
          mkdir _site
          mkdir _site/target
          mkdir _site/target/generated
          mv index.html _site/index.html
          mv target/generated/* _site/target/generated
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4